#!/bin/sh
#irun -clean -sysc model.cpp model.v tb.v +access+rwc -timescale 1ns/1ns

# To generate shell file automatically
#     irun -compile -sysc model.cpp
#     ncshell -suffix v -import systemc -into verilog model

clean; rm -f model.v
irun -compile -sysc model.cpp
ncshell -suffix v -import systemc -into verilog model
irun -sysc model.cpp model.v tb.v +access+rwc -timescale 1ns/1ns
